apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - https://github.com/truedevops/backstage/blob/main/backstage-catalog.yaml
    - https://github.com/truedevops/backstage/blob/main/groups.yaml
    - https://github.com/truedevops/backstage/blob/main/users.yaml
